"""new migration

Revision ID: 2a7d4809a54c
Revises: 
Create Date: 2022-03-08 16:24:08.318185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7d4809a54c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=80), nullable=False),
    sa.Column('item_cost', sa.Float(), nullable=False),
    sa.Column('item_description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('restaurant',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=100), nullable=False),
    sa.Column('restaurant_email', sa.String(length=40), nullable=False),
    sa.Column('restaurant_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('restaurant_id'),
    sa.UniqueConstraint('restaurant_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant')
    op.drop_table('menu_items')
    # ### end Alembic commands ###
